apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: djdo6m49k-nodejs
  janus-idp.io/tekton: djdo6m49k-nodejs
  backstage.io/kubernetes-id: djdo6m49k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: djdo6m49k-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
