apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: djdo6m49k-nodejs 
  janus-idp.io/tekton: djdo6m49k-nodejs
  backstage.io/kubernetes-id: djdo6m49k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: djdo6m49k-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml